version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: assistive_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - assistive_ai_net

volumes:
  assistive_ai_data:

networks:
  assistive_ai_net:
    name: assistive_ai_net
