services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: assistive_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - assistive_ai_net

  # app:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.app
  #   container_name: assistive_app
  #   ports:
  #     - "19000:19000"  # Metro bundler
  #     - "19001:19001"  # DevTools
  #     - "19002:19002"  # Tunnel
  #     - "8081:8081"    # Web
  #   volumes:
  #     - ./app:/app
  #   networks:
  #     - assistive_ai_net

volumes:
  assistive_ai_data:

networks:
  assistive_ai_net:
    name: assistive_ai_net
